//
//  SettingsConstants.h
//  TidyTime
//
//  Created by Rudi Strahl on 12-07-30.
//
//

#ifndef TidyTime_SettingsConstants_h
#define TidyTime_SettingsConstants_h

#define SETTINGS_KEY_CLOCK_IS_TIME_LAPSE        @"CLOCK_IS_TIME_LAPSE"
#define SETTINGS_KEY_CLOCK_MULTIPLIER           @"CLOCK_MULTIPLIER"
#define SETTINGS_KEY_USE_CELSIUS                @"USE_CELSIUS"
#define SETTINGS_KEY_USE_SYSTEM_TIME_FORMAT     @"USE_SYSTEM_TIME_FORMAT"
#define SETTINGS_KEY_USE_24_HOUR_CLOCK          @"USE_24_HOUR_CLOCK"
#define SETTINGS_KEY_SHOW_DATE                  @"SHOW_DATE"
#define SETTINGS_KEY_SHOW_TEMP                  @"SHOW_TEMPERATURE"
#define SETTINGS_KEY_SHOW_NEXT_ALARM            @"SHOW_NEXT_ALARM"
#define SETTINGS_KEY_FADE_IN_MUSIC              @"FADE_IN_MUSIC"
#define SETTINGS_KEY_SHOW_FROST_FRAME           @"SHOW_FROST_FRAME"
#define SETTINGS_KEY_LOCATION_BASED_WEATHER     @"LOCATION_BASED_WEATHER"
#define SETTINGS_KEY_CURRENT_SEASON             @"CURRENT_SEASON"
#define SETTINGS_KEY_CURRENT_CLOUDS             @"CURRENT_CLOUDS"
#define SETTINGS_KEY_CURRENT_RAIN               @"CURRENT_RAIN"
#define SETTINGS_KEY_CURRENT_SNOW               @"CURRENT_SNOW"
#define SETTINGS_KEY_CURRENT_LIGHTNING          @"CURRENT_LIGHTNING"
#define SETTINGS_KEY_CURRENT_FOG                @"CURRENT_FOG"
#define SETTINGS_KEY_FIRST_TIME_ON_HOME_SCREEN  @"FIRST_TIME_ON_HOME_SCREEN"

#endif
